In [9]:
from utils.datainput import initializeUnif
import pandas as pd
import numpy as np

In [10]:
input11, output11 = initializeUnif(50, 1, 1, 50, 100)
df11 = pd.DataFrame(np.hstack((input11, output11)), columns=["X1", "Y1"])

In [11]:
input21, output21 = initializeUnif(50, 2, 1, 50, 100)
df21 = pd.DataFrame(np.hstack((input21, output21)), columns=["X1", "X2", "Y1"])

In [12]:
df11

           X1         Y1
0   61.985479  94.126175
1   65.370642  86.087203
2   58.022022  85.023597
3   77.906915  50.868607
4   59.957844  90.343284
5   97.864351  69.339685
6   62.149364  97.463760
7   61.528745  98.352890
8   83.918320  93.706545
9   74.722116  78.889327
10  84.500944  73.991972
11  96.327480  51.462470
12  90.379068  63.258620
13  68.728352  95.493949
14  81.987767  72.552061
15  76.286325  97.243306
16  69.999092  77.247511
17  57.035628  95.965145
18  80.707954  69.701272
19  50.475367  79.669413
20  72.602847  89.429760
21  84.570644  59.752804
22  55.722419  57.410657
23  61.598265  52.452366
24  79.977526  67.800285
25  69.132668  64.358861
26  72.000219  85.412296
27  86.528907  72.471019
28  55.356917  76.807044
29  61.967379  77.840637
30  74.955386  81.186953
31  98.975741  78.425998
32  95.803375  55.300052
33  78.505040  66.443844
34  61.025935  55.979340
35  68.403103  61.326695
36  67.303733  53.272229
37  58.896689  93.401027
38  75.988095  79.079560
39  67.507556  83.646489
40  72.775477  85.606540
41  70.396940  83.589413
42  63.546464  61.839933
43  89.796028  88.742167
44  52.863129  53.187491
45  57.421420  55.108116
46  50.953826  77.305676
47  68.627940  83.311338
48  79.761209  72.999233
49  53.286290  98.432903

In [13]:
df21

           X1         X2         Y1
0   96.429848  82.589391  83.953174
1   96.913395  72.656840  72.354013
2   70.642329  89.263805  72.659579
3   60.378656  95.890373  79.706238
4   75.048426  90.971004  67.660135
5   50.084862  71.483731  63.390927
6   71.868066  93.324448  82.287966
7   89.067856  81.368023  69.290774
8   92.272319  99.729017  59.295978
9   63.101540  51.479134  67.787104
10  65.177450  51.549924  78.952120
11  84.312283  50.414765  60.654198
12  55.592202  74.393116  67.012009
13  79.097039  56.392683  69.891697
14  66.886588  73.790422  62.768869
15  76.755039  64.488512  62.983482
16  86.849614  54.184465  79.130135
17  91.966722  80.452867  63.897025
18  62.387213  99.299035  93.750248
19  98.421632  52.548053  71.559029
20  77.809457  59.895668  83.460955
21  72.741377  87.813942  83.600808
22  85.462129  56.627910  93.367869
23  56.160739  71.459224  94.214370
24  56.045514  96.457528  69.048609
25  83.304518  86.642098  55.054800
26  83.071760  65.309984  79.528174
27  63.364017  59.692130  63.606826
28  80.299561  86.744072  91.963889
29  72.772983  88.411415  64.042587
30  57.993815  52.854263  91.610327
31  66.697906  85.215761  69.038126
32  73.411774  76.533613  64.181143
33  72.924754  88.093672  67.079423
34  58.303655  92.581650  54.357237
35  65.385034  72.933719  99.285909
36  96.928241  89.871902  88.004522
37  51.773639  99.044730  50.943914
38  58.118833  54.596029  84.497046
39  58.331199  92.883574  78.960311
40  99.025940  94.532950  94.809847
41  88.155037  65.498320  69.890608
42  54.096799  78.430070  93.969122
43  73.063828  56.746959  77.147068
44  58.797999  54.124486  55.174136
45  79.549061  66.749220  80.498916
46  72.177579  80.533453  93.161095
47  92.692830  67.773803  61.183720
48  61.129376  92.746655  82.217509
49  75.020266  65.262771  73.978103

In [14]:
df11.to_csv('1i1o.csv', index=False)
df21.to_csv('2i1o.csv', index=False)